spring:
  application:
    name: forty-nav-api
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cg_db
    username: root
    password: 123456
server:
  port: 8000

logging:
  level:
    org:
      mybatis: debug

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl