spring:
  application:
    name: forty-nav-api
  profiles:
    active: dev

server:
  port: 8443

setting:
  wechat:
    app-id: wx188064afe4d0e189
    app-secret:  878524a515125108963cb3819a3e3494
  secret-key: 55s9q11a!!4)s,1aA@DF(ScACX)A__=-sczc)dkD987s230a==
